[2023-10-02T03:15:07.779+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.load_to_postgres scheduled__2020-07-02T06:00:00+00:00 [queued]>
[2023-10-02T03:15:07.791+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.load_to_postgres scheduled__2020-07-02T06:00:00+00:00 [queued]>
[2023-10-02T03:15:07.791+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-02T03:15:07.812+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2020-07-02 06:00:00+00:00
[2023-10-02T03:15:07.820+0000] {standard_task_runner.py:57} INFO - Started process 3773 to run task
[2023-10-02T03:15:07.824+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-Postgres', 'load_to_postgres', 'scheduled__2020-07-02T06:00:00+00:00', '--job-id', '727', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_pg.py', '--cfg-path', '/tmp/tmpqul_m57v']
[2023-10-02T03:15:07.826+0000] {standard_task_runner.py:85} INFO - Job 727: Subtask load_to_postgres
[2023-10-02T03:15:07.886+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.load_to_postgres scheduled__2020-07-02T06:00:00+00:00 [running]> on host 537710aea1a2
[2023-10-02T03:15:08.001+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-Postgres' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2020-07-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-07-02T06:00:00+00:00'
[2023-10-02T03:15:08.002+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: load_data_to_postgres() missing 1 required positional argument: 'postgres_hook'
[2023-10-02T03:15:08.012+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-Postgres, task_id=load_to_postgres, execution_date=20200702T060000, start_date=20231002T031507, end_date=20231002T031508
[2023-10-02T03:15:08.033+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 727 for task load_to_postgres (load_data_to_postgres() missing 1 required positional argument: 'postgres_hook'; 3773)
[2023-10-02T03:15:08.075+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-02T03:15:08.094+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
