[2023-10-02T00:07:01.504+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.extract_to_gcs scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2023-10-02T00:07:01.515+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.extract_to_gcs scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2023-10-02T00:07:01.515+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-02T00:07:01.538+0000] {taskinstance.py:1327} INFO - Executing <Task(WebToGCSHKOperator): extract_to_gcs> on 2019-04-02 06:00:00+00:00
[2023-10-02T00:07:01.545+0000] {standard_task_runner.py:57} INFO - Started process 363 to run task
[2023-10-02T00:07:01.548+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-Postgres', 'extract_to_gcs', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '656', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_pg.py', '--cfg-path', '/tmp/tmpa1aacgar']
[2023-10-02T00:07:01.551+0000] {standard_task_runner.py:85} INFO - Job 656: Subtask extract_to_gcs
[2023-10-02T00:07:01.618+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.extract_to_gcs scheduled__2019-04-02T06:00:00+00:00 [running]> on host 537710aea1a2
[2023-10-02T00:07:01.752+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-Postgres' AIRFLOW_CTX_TASK_ID='extract_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2019-04-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-04-02T06:00:00+00:00'
[2023-10-02T00:07:01.754+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-02T00:07:01.754+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-02T00:07:01.755+0000] {Web_To_GCS_Hook.py:67} INFO - Execute downloading of file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-04.csv.gz to gs://practice18//green_tripdata_2019-04.csv.gz
[2023-10-02T00:07:11.847+0000] {Web_To_GCS_Hook.py:79} INFO - File written to temporary directory: /tmp/tmp9qtddruj/green_tripdata_2019-04.csv.gz
[2023-10-02T00:07:13.793+0000] {logging_mixin.py:150} INFO -    VendorID lpep_pickup_datetime  ... trip_type congestion_surcharge
0         2  2019-04-01 00:18:40  ...         1                 2.75
1         2  2019-04-01 00:18:24  ...         1                 0.00
2         2  2019-04-01 00:31:24  ...         1                 0.00
3         2  2019-04-01 00:48:30  ...         1                 0.00
4         1  2019-04-01 00:04:42  ...         1                 0.00

[5 rows x 20 columns]
[2023-10-02T00:07:13.793+0000] {logging_mixin.py:150} INFO - (514392, 20)
[2023-10-02T00:07:18.353+0000] {Web_To_GCS_Hook.py:90} INFO - Parquet: green_tripdata_2019-04.csv
[2023-10-02T00:07:54.105+0000] {gcs.py:538} INFO - File /tmp/tmp9qtddruj/green_tripdata_2019-04.csv uploaded to green/green_tripdata_2019-04.csv in practice18 bucket
[2023-10-02T00:07:54.106+0000] {Web_To_GCS_Hook.py:105} INFO - Loaded file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-04.csv.gz to gs://practice18//green/green_tripdata_2019-04.csv
[2023-10-02T00:07:54.153+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-Postgres, task_id=extract_to_gcs, execution_date=20190402T060000, start_date=20231002T000701, end_date=20231002T000754
[2023-10-02T00:07:54.222+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-02T00:07:54.254+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-02T15:24:31.305+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.extract_to_gcs scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2023-10-02T15:24:31.476+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.extract_to_gcs scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2023-10-02T15:24:31.477+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-02T15:24:31.651+0000] {taskinstance.py:1327} INFO - Executing <Task(WebToGCSHKOperator): extract_to_gcs> on 2019-04-02 06:00:00+00:00
[2023-10-02T15:24:31.661+0000] {standard_task_runner.py:57} INFO - Started process 6109 to run task
[2023-10-02T15:24:31.665+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-Postgres', 'extract_to_gcs', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '966', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_pg.py', '--cfg-path', '/tmp/tmpi2sj6tfl']
[2023-10-02T15:24:31.667+0000] {standard_task_runner.py:85} INFO - Job 966: Subtask extract_to_gcs
[2023-10-02T15:24:31.774+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.extract_to_gcs scheduled__2019-04-02T06:00:00+00:00 [running]> on host 537710aea1a2
[2023-10-02T15:24:31.998+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-Postgres' AIRFLOW_CTX_TASK_ID='extract_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2019-04-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-04-02T06:00:00+00:00'
[2023-10-02T15:24:32.000+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-02T15:24:32.000+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-02T15:24:32.002+0000] {Web_To_GCS_Hook.py:67} INFO - Execute downloading of file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-04.csv.gz to gs://practice18//green_tripdata_2019-04.csv.gz
[2023-10-02T15:25:42.765+0000] {Web_To_GCS_Hook.py:79} INFO - File written to temporary directory: /tmp/tmpox1qs_u8/green_tripdata_2019-04.csv.gz
[2023-10-02T15:25:47.504+0000] {logging_mixin.py:150} INFO -    VendorID lpep_pickup_datetime  ... trip_type congestion_surcharge
0         2  2019-04-01 00:18:40  ...         1                 2.75
1         2  2019-04-01 00:18:24  ...         1                 0.00
2         2  2019-04-01 00:31:24  ...         1                 0.00
3         2  2019-04-01 00:48:30  ...         1                 0.00
4         1  2019-04-01 00:04:42  ...         1                 0.00

[5 rows x 20 columns]
[2023-10-02T15:25:47.504+0000] {logging_mixin.py:150} INFO - (514392, 20)
[2023-10-02T15:25:52.257+0000] {Web_To_GCS_Hook.py:90} INFO - Parquet: green_tripdata_2019-04.csv
[2023-10-02T15:26:57.007+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 721, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1075, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.7/http/client.py", line 997, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 721, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1075, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.7/http/client.py", line 997, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/plugins/web/operators/Web_To_GCS_Hook.py", line 58, in execute
    self._copy_file_object(gcs_hook)
  File "/opt/airflow/plugins/web/operators/Web_To_GCS_Hook.py", line 99, in _copy_file_object
    gzip=False,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 533, in upload
    partial(blob.upload_from_filename, filename=filename, content_type=mime_type, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 490, in _call_with_retry
    f()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2697, in upload_from_filename
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2553, in upload_from_file
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2384, in _do_upload
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2215, in _do_resumable_upload
    response = upload.transmit_next_chunk(transport, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/upload.py", line 516, in transmit_next_chunk
    retriable_request, self._get_status_code, self._retry_strategy
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/_request_helpers.py", line 178, in wait_and_retry
    raise error
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/upload.py", line 508, in retriable_request
    method, url, data=payload, headers=headers, timeout=timeout
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/transport/requests.py", line 555, in request
    **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))
[2023-10-02T15:26:58.844+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-Postgres, task_id=extract_to_gcs, execution_date=20190402T060000, start_date=20231002T152431, end_date=20231002T152658
[2023-10-02T15:26:59.123+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 966 for task extract_to_gcs (('Connection aborted.', timeout('The write operation timed out')); 6109)
[2023-10-02T15:26:59.184+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-02T15:26:59.366+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
