[2023-10-02T00:05:50.583+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.download_file_from_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-02T00:05:50.595+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.download_file_from_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-02T00:05:50.595+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2023-10-02T00:05:50.693+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToLocalFilesystemOperator): download_file_from_gcs> on 2019-03-02 06:00:00+00:00
[2023-10-02T00:05:50.701+0000] {standard_task_runner.py:57} INFO - Started process 339 to run task
[2023-10-02T00:05:50.705+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-Postgres', 'download_file_from_gcs', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '654', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_pg.py', '--cfg-path', '/tmp/tmp2aaern2d']
[2023-10-02T00:05:50.707+0000] {standard_task_runner.py:85} INFO - Job 654: Subtask download_file_from_gcs
[2023-10-02T00:05:50.864+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.download_file_from_gcs scheduled__2019-03-02T06:00:00+00:00 [running]> on host 537710aea1a2
[2023-10-02T00:05:51.013+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-Postgres' AIRFLOW_CTX_TASK_ID='download_file_from_gcs' AIRFLOW_CTX_EXECUTION_DATE='2019-03-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-03-02T06:00:00+00:00'
[2023-10-02T00:05:51.014+0000] {gcs_to_local.py:111} INFO - Executing download: practice18, green_tripdata2019-03.csv, /opt/***/green_tripdata2019-03.csv
[2023-10-02T00:05:51.016+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-02T00:05:51.016+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-02T00:05:52.068+0000] {gcs.py:353} ERROR - Download attempt of object: green_tripdata2019-03.csv from practice18 has failed. Attempt: 1, max 1.
[2023-10-02T00:05:52.068+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 1109, in download_blob_to_file
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 984, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 238, in consume
    retriable_request, self._get_status_code, self._retry_strategy
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 219, in retriable_request
    self._process_response(result)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/_download.py", line 189, in _process_response
    response, _ACCEPTABLE_STATUS_CODES, self._get_status_code
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/_helpers.py", line 113, in require_status_code
    *status_codes
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_local.py", line 125, in execute
    hook.download(bucket_name=self.bucket, object_name=self.object_name, filename=self.filename)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 340, in download
    blob.download_to_filename(filename, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1270, in download_to_filename
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 1112, in download_blob_to_file
    _raise_from_invalid_response(exc)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 4373, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.NotFound: 404 GET https://storage.googleapis.com/download/storage/v1/b/practice18/o/green_tripdata2019-03.csv?alt=media: No such object: practice18/green_tripdata2019-03.csv: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
[2023-10-02T00:05:52.079+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-Postgres, task_id=download_file_from_gcs, execution_date=20190302T060000, start_date=20231002T000550, end_date=20231002T000552
[2023-10-02T00:05:52.147+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 654 for task download_file_from_gcs (404 GET https://storage.googleapis.com/download/storage/v1/b/practice18/o/green_tripdata2019-03.csv?alt=media: No such object: practice18/green_tripdata2019-03.csv: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>); 339)
[2023-10-02T00:05:52.159+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-02T00:05:52.189+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
